version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: insight-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Apple@123
      MONGO_INITDB_DATABASE: insight_db
    ports:
      - "27017:27017"
    volumes:
      - /Users/manishsanger/docker-data/mongodb:/data/db
      - ./sample-data:/docker-entrypoint-initdb.d
    networks:
      - insight-network

  officer-insight-api:
    build: ./officer-insight-api
    container_name: insight-officer-api
    restart: unless-stopped
    ports:
      - "8650:8650"
    environment:
      MONGODB_URI: mongodb://admin:Apple%40123@mongodb:27017/insight_db?authSource=admin
      SPEECH2TEXT_API_URL: http://speech2text-service:8652
      SPEECH2TEXT_API_TOKEN: insight_speech_token_2024
      OLLAMA_URL: http://host.docker.internal:11434
      # Image management configuration
      IMAGES_UPLOAD_BASE_PATH: /app/data/images
      IMAGES_ALLOWED_EXTENSIONS: jpg,jpeg,png,gif,bmp,tiff,webp
      IMAGES_MAX_FILE_SIZE: 16777216  # 16MB
    depends_on:
      - mongodb
      - speech2text-service
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/officer-insight-api:/app/data

  car-identifier-service:
    build: ./car-identifier-service
    container_name: insight-car-identifier
    restart: unless-stopped
    ports:
      - "8653:8653"
    environment:
      MONGODB_URI: mongodb://admin:Apple%40123@mongodb:27017/insight_db?authSource=admin
      OLLAMA_URL: http://host.docker.internal:11434
      VISION_MODEL: gemma3:12b
      MODEL_TIMEOUT: 180
      CORS_ORIGINS: http://localhost:8651,http://localhost:3000
      ALLOWED_EXTENSIONS: jpg,jpeg,png,gif,bmp,webp
      MAX_CONTENT_LENGTH: 16777216
      EXTRACTION_FIELDS: vehicle_registration,vehicle_make,vehicle_color,vehicle_model
    depends_on:
      - mongodb
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/car-identifier-service:/app/data

  admin-ui:
    build: ./admin-ui
    container_name: insight-admin-ui
    restart: unless-stopped
    ports:
      - "8651:8651"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8650
      REACT_APP_CAR_IDENTIFIER_URL: http://localhost:8653
      REACT_APP_DOC_READER_URL: http://localhost:8654
      NODE_ENV: production
    depends_on:
      - officer-insight-api
      - car-identifier-service
      - doc-reader-service
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/admin-ui:/app/data

  speech2text-service:
    build: ./speech2text-service
    container_name: insight-speech2text
    restart: unless-stopped
    ports:
      - "8652:8652"
    environment:
      API_TOKEN: insight_speech_token_2024
      WHISPER_MODEL: base
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/speech2text-service:/app/audio_files

  doc-reader-service:
    build: ./doc-reader-service
    container_name: insight-doc-reader
    restart: unless-stopped
    ports:
      - "8654:8654"
    environment:
      MONGODB_URI: mongodb://admin:Apple%40123@mongodb:27017/insight_db?authSource=admin
      OLLAMA_URL: http://host.docker.internal:11434
      VISION_MODEL: gemma3:12b
      MODEL_TIMEOUT: 180
      CORS_ORIGINS: http://localhost:8651,http://localhost:3000
      ALLOWED_EXTENSIONS: jpg,jpeg,png,gif,bmp,webp,pdf
      MAX_CONTENT_LENGTH: 16777216
      EXTRACTION_FIELDS: document_type,name,date_of_birth,country,date_of_issue,expiry_date,address,gender,place_of_birth,issuing_authority,nationality,pin_code,person_image
      JWT_SECRET_KEY: your-secret-key-here
      JWT_ACCESS_TOKEN_EXPIRES: 3600
    depends_on:
      - mongodb
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/doc-reader-service:/app/data

networks:
  insight-network:
    driver: bridge

volumes:
  mongodb_data:
  officer_api_data:
  car_identifier_data:
  admin_ui_data:
  speech2text_data:
  doc_reader_data:
