version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: insight-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Apple@123
      MONGO_INITDB_DATABASE: insight_db
    ports:
      - "27017:27017"
    volumes:
      - /Users/manishsanger/docker-data/mongodb:/data/db
      - ./sample-data:/docker-entrypoint-initdb.d
    networks:
      - insight-network

  officer-insight-api:
    build: ./officer-insight-api
    container_name: insight-officer-api
    restart: unless-stopped
    ports:
      - "8650:8650"
    environment:
      MONGODB_URI: mongodb://admin:Apple%40123@mongodb:27017/insight_db?authSource=admin
      SPEECH2TEXT_API_URL: http://speech2text-service:8652
      SPEECH2TEXT_API_TOKEN: insight_speech_token_2024
      OLLAMA_URL: http://host.docker.internal:11434
    depends_on:
      - mongodb
      - speech2text-service
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/officer-insight-api:/app/data

  admin-ui:
    build: ./admin-ui
    container_name: insight-admin-ui
    restart: unless-stopped
    ports:
      - "8651:8651"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8650
      NODE_ENV: production
    depends_on:
      - officer-insight-api
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/admin-ui:/app/data

  speech2text-service:
    build: ./speech2text-service
    container_name: insight-speech2text
    restart: unless-stopped
    ports:
      - "8652:8652"
    environment:
      API_TOKEN: insight_speech_token_2024
      WHISPER_MODEL: base
    networks:
      - insight-network
    volumes:
      - /Users/manishsanger/docker-data/speech2text-service:/app/audio_files

networks:
  insight-network:
    driver: bridge

volumes:
  mongodb_data:
  officer_api_data:
  admin_ui_data:
  speech2text_data:
